require 'socket'

require_relative 'ogn_client/version'
require_relative 'ogn_client/errors'
require_relative 'ogn_client/aprs'
require_relative 'ogn_client/message'
require_relative 'ogn_client/messages/comment'
require_relative 'ogn_client/messages/receiver_beacon'
require_relative 'ogn_client/messages/receiver_status'
require_relative 'ogn_client/messages/sender_beacon'
